# FETCHES
### Fetch single user
GET localhost:8080/customer/1
### Get all users
GET localhost:8080/customer/find-all

### Fetch by first name
GET localhost:8080/customer/first-name/lexie

### Fetch by last name
GET localhost:8080/customer/last-name/Brown

### Fetch by phone number
GET localhost:8080/customer/phone-number/612

### Fetch by email
GET localhost:8080/customer/email/612

### Update customer details
PUT localhost:8080/customer/update/1
Content-Type: application/json

{
  "car_information": "Chevy"
}
